#
# Dockerfile 'registry-ui'
#
FROM raspidocker/lang-java
MAINTAINER Michael Eichinger <raspidocker@mgeo.de>

RUN apt-get install -y groovy

VOLUME [ "/var/lib/docker/registry/data:/var/lib/registry" ]
