#!/usr/bin/env bash
ARGS=$@
INIT_DIR="/etc/docker/up.d"
if [ $(ls ${INIT_DIR}/*.sh | wc -l) -gt 0 ]; then
	chmod a+x ${INIT_DIR}/*
	for initscript in ${INIT_DIR}/*.sh; do
		echo -e "[RUN] ${initscript}"
		${initscript}
	done
fi