#
# Dockerfile 'lang-java'
#
FROM raspidocker/os-resin
MAINTAINER Michael Eichinger <raspidocker@mgeo.de>

# INSTALL
RUN     apt-get update && apt-get install -y --no-install-recommends apt-utils git openjdk-7-jdk groovy

